# Generated by Django 5.1 on 2024-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
