# Generated by Django 5.1 on 2024-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0002_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
