# Generated by Django 5.1 on 2024-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0004_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_lost',
            field=models.BooleanField(default=False),
        ),
    ]
