# Generated by Django 5.1 on 2024-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0005_student_id_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_lost',
            field=models.BooleanField(default=True),
        ),
    ]
