# Generated by Django 5.1 on 2024-08-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0008_alter_student_id_lost_alter_student_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
