# Generated by Django 5.1 on 2024-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0009_alter_student_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_lost',
            field=models.BooleanField(default=False),
        ),
    ]
