# Generated by Django 5.1 on 2024-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0010_alter_student_id_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_lost',
            field=models.BooleanField(default=True),
        ),
    ]
