# Generated by Django 5.1 on 2024-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0012_alter_student_id_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
