# Generated by Django 5.1 on 2024-08-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0013_student_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
    ]
