# Generated by Django 5.1 on 2024-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0016_remove_student_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
