# Generated by Django 5.1 on 2024-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0017_student_year_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMISStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
    ]
