# Generated by Django 5.1 on 2024-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0018_amisstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amisstudent',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='amisstudent',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amisstudent',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='amisstudent',
            name='year_of_study',
            field=models.CharField(max_length=20),
        ),
    ]
