# Generated by Django 5.1 on 2024-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0019_remove_amisstudent_payment_status_amisstudent_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amisstudent',
            name='id_printed',
            field=models.BooleanField(default=False),
        ),
    ]
