# Generated by Django 5.1 on 2024-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0021_lostidreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='amisstudent',
            name='has_printed_id',
            field=models.BooleanField(default=False),
        ),
    ]
