# Generated by Django 5.1 on 2024-08-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0022_amisstudent_has_printed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostidreport',
            old_name='student',
            new_name='student_id',
        ),
    ]
