# Generated by Django 5.1 on 2024-08-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0023_rename_student_lostidreport_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amisstudent',
            name='has_printed_id',
        ),
        migrations.DeleteModel(
            name='LostIDReport',
        ),
    ]
