# Generated by Django 5.1 on 2024-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0024_remove_amisstudent_has_printed_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amisstudent',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
