# Generated by Django 5.1 on 2024-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0025_amisstudent_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='amisstudent',
            name='id_replacement_requested',
            field=models.BooleanField(default=False),
        ),
    ]
