# Generated by Django 5.1 on 2024-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0026_amisstudent_id_replacement_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='amisstudent',
            name='id_lost',
            field=models.BooleanField(default=False),
        ),
    ]
