# Generated by Django 5.1 on 2024-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0027_amisstudent_id_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='loss_reports/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
