# Generated by Django 5.1 on 2024-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0028_lossreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreport',
            name='id_lost',
            field=models.BooleanField(default=False),
        ),
    ]
