# Generated by Django 5.1 on 2024-09-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0029_lossreport_id_lost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossreport',
            name='id_lost',
        ),
    ]
